@extends('frontend.master')
@section('content')
@include('frontend.partials.hero-section')
@include('frontend.partials.latest-updates')
@include('frontend.partials.blog-section')
@include('frontend.partials.news-letter')
@include('frontend.partials.article-section')
@include('frontend.partials.gallery-section')    
@endsection